"""add weight tracking and extend user settings

Revision ID: 1496b4b321b9
Revises: 
Create Date: 2024-11-26 11:43:23.522390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1496b4b321b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('starting_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('starting_bodyfat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('height_inches', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('target_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('target_bodyfat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('goal_months', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_settings', schema=None) as batch_op:
        batch_op.drop_column('goal_months')
        batch_op.drop_column('target_bodyfat')
        batch_op.drop_column('target_weight')
        batch_op.drop_column('height_inches')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')
        batch_op.drop_column('starting_bodyfat')
        batch_op.drop_column('starting_weight')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
